# Generated by Django 4.0.4 on 2022-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='faltu',
            field=models.CharField(default='', max_length=10),
        ),
    ]
