# Generated by Django 3.2.7 on 2022-04-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complain_response_date',
        ),
    ]
