# Generated by Django 3.2.7 on 2022-04-23 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_complain_complain_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='parent',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty'),
        ),
    ]
