# Generated by Django 3.2.7 on 2022-04-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_complain_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(default=' ', max_length=5000, null=True),
        ),
    ]
