# Generated by Django 3.2.7 on 2022-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20220423_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.IntegerField(default=' ', max_length=1, null=True),
        ),
    ]
