# Generated by Django 4.1.2 on 2022-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_remove_complain_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
